### ISSUE TITLE
Networking - New network creation.

### ISSUE THREAD

**Issue by tatuzemdp** [DaVieS007/bhyve-webadmin#19]
Hi there, running release 1.2. When creating a new network, seems that PHY interfaces is not added directly after creation, hence I need to edit and select the phy interface again to make it part of the bridge. Also when removing a network, the bridge (in this case was bridge300) is not deleted, needing manual intervention.
Best regards and great software.

**Comment by DaVieS007** [comment]
Hi!

Some of network functions is takes action when the VM is started and some functions is just delayed
Making/Destroying bridges including add/remove interfaces causes network lagg the most of the time, this is a perfectly normal behaviour. 

To avoid unnecessary interruptions the software may keep-up and maintains bridge interfaces and might be add PHY netif when the VM is started.

Can you please test against your issue? if the PHY interface remains detached when VM already booted?
Thank You!
