### ISSUE TITLE
Password change not working

### ISSUE THREAD

**Issue by mayrk** [DaVieS007/bhyve-webadmin#22]
Whatever combination of small letters, capital letters, digits and everything 
you can enter with the keyboard i try in the "change password" account settings i always receive the message
"password does not meet the requirements".

I usually use at least ten characters and usually any (or at least three) of the character types mentioned above. 

i even tried to change just one single character of the created "admin" Password
during setup, but even this is rejected.

I could not find any hint for "the requirements". What am i doing wrong ? :-|

**Comment by DaVieS007** [comment]
I close this due it solved with the first release.
