### ISSUE TITLE
Windows 10 VM - setup reboots vm with virtio disk

### ISSUE THREAD

**Issue by mayrk** [DaVieS007/bhyve-webadmin#23]
I tried to deploy to windows virtual Machines as described in ==> https://bhyve.npulse.net/deploy_windows <==.
I used 21H2 (19044.1266 ISO to be precise) and the (latest ?) Virtio ISO linked in the top of the manual.

First i attached the virtual system disk as described on VirtIO, but when windows setup loads the driver, the VM 
reboots immediately.

With the AHCI Option for the disk the windows installation worked perfect without any issues.

My FreeBSD System is 14.0-current if that matters for this issue.

**Comment by DaVieS007** [comment]
Thanks your report, I have seen this issue when I used to a wrong driver as virt/io. There are multiple viostor driver and you need to pickup the latest one for win10.

Please report back if you have any update on this case.

**Comment by mayrk** [comment]
I tried this several times with the viostor driver for Win10/amd64 but always with the result that the vm rebooted.
I will try older Win10 Versions the next day to find the cause ... it could also be a problem in the bhyve in 14.0-current ...

**Comment by mayrk** [comment]
I tried today an older version (18363 aka W10 1909) as OEM iso with similar settings.
The viostor driver gets loaded, the machine crashes after the disk was selected, the fist 100mb boot partition was created on the disk.

Interestingly, all Windows VM show a hardware change notification (error code 0xC004F211) in the activation settings, although they have not been activated yet ...
