### ISSUE TITLE
NoVNC Console - Stuck on 'Connecting...'?

### ISSUE THREAD

**Issue by HardwareExtreme** [DaVieS007/bhyve-webadmin#25]
So I created new VM, started it up, but NoVNC is stuck on Connecting when I try to launch the console. BVCP says that it is running in web interface so not entirely certain what the issue is.

This is on a FreeBSD 13.0 AMD64 host with FreeBSD 13.0 AMD64 in the VM.

**Comment by DaVieS007** [comment]
bhyve only allows one VNC session per VM so please ensure that no other VNC windows are active at the same time with the same VM. VNC uses websockets so some debug informations (F12 (Network) on Chrome) browser would be helpful to solve this case.

VNC usually 'just' works out-of-the-box Im interested what the cause in this case, let me know if you have updates.

**Comment by HardwareExtreme** [comment]
I tried on both Firefox/Opera, same result. Not sure what debug information you want, or how I even access it on Firefox.

**Comment by DaVieS007** [comment]
Can you please provide a screenshot from the details page, which it showing the VM settings and it's state (running), please ensure that no private informations shared or passwords. You can email me directly to davies@npulse.net

**Comment by DaVieS007** [comment]
Thanks to HardwareExtreme we identified the bug and seems like the problem came from that the hostname was uppercase, but the configuration file does not accept uppercase as the key.
