### ISSUE TITLE
upgrade to 1.6 breaks frontend

### ISSUE THREAD

**Issue by RanceH** [DaVieS007/bhyve-webadmin#26]
I had a 1.4 install running well, and performed the upgrade to 1.6 following the instructions.

After upgrade to 1.6 backend and helper started correctly, but foreground did not.

foreground starts, records a pid in the pid file and crashes leaving the vms running, but uncontrollable.  Tried rebooting, and various attempts at logging/ troubleshooting.  Ended up downgrading to restore the service.

troubleshooting tips welcome, and I can try again.

**Comment by HardwareExtreme** [comment]
Have same issue, ended up reverting to 1.4. Webpage is inaccessable but VMs still autostart and run in backround.

**Comment by DaVieS007** [comment]
Thank you for reporting this, we are placing signature into binaries to ensure no modification has been made which is critical part of the main security, now by mistake the binaries does not have one, thats why the software could not start.

This issue revealed that we should rework our publishing policy and separate branches like STABLE and NEWEST.
The VMs are independent from the frontend so upgrade and downgrade does not affect them, you can switch versions anytime.

I ensure everyone we are going to patch this out within minutes.

**Comment by DaVieS007** [comment]
I confirm that the fixed version is available by 1.6a since no changes are made in the code the version remains 1.6.

Please confirm its working as intended.

**Comment by HardwareExtreme** [comment]
Update 1.6a seems to have fixed it, upgraded and webpage frontend appears to be working.

**Comment by RanceH** [comment]
I just had a chance to review this.  I also can confirm that the issue is resolved.

Thanks for your quick response.  Much appreciated.
