### ISSUE TITLE
Linux vm setup in infinite boot loop

### ISSUE THREAD

**Issue by bbking78** [DaVieS007/bhyve-webadmin#27]
I am trying to set up a linux vm with either ubuntu-20.04.3-live-server-amd64.iso or alpine-standard-3.15.0-x86.iso / alpine-virt-3.15.0-x86.iso  / alpine-virt-3.15.0-x86_64.iso but none of those will even boot.
I tried to create the disks either with SATA/AHCI or Virt/IO and the network with either Intel Pro 100 or Virt/IO but every combination leads to an invinite boot loop.

Any ideas on this?

(I also have only empty charts in the "Systm information" menue and somehow my host disk is shown as 138.12GB although it only has 67GB)

otherwise very cool project!

**Comment by DaVieS007** [comment]
Thank you to submitting this!
Can you see any error on logs files located at /vms/logs (by default)?
When do you facing boot loop before installation or when the installation done?

**Comment by DaVieS007** [comment]
I have tested both alpine linux and Ubuntu server you mentioned, also I installed the last one without any problems on my box. No boot loop, no need for magic tricks, worked out of the box. is dmesg tells you anything, maybe crash? OOM?

**Comment by DaVieS007** [comment]
I willing to go for any type of conversation with this issue, reach me out at davies@npulse.net.

**Comment by DaVieS007** [comment]
I contacted to bbking78 directly and the bug came from a unique hardware & software combination, kldload vmm.ko solved the issue, closing.
