### ISSUE TITLE
user cant create a vm

### ISSUE THREAD

**Issue by outbackdingo** [DaVieS007/bhyve-webadmin#33]
is it true that a user cant create a vm ? you must be an administrator ? meaning if i had customer A) he cant create a vm ubnless hes an admnin, if hes an admin he cant see everyones vms ?

**Comment by DaVieS007** [comment]
yes, it supposed to be work that way.

**Comment by outbackdingo** [comment]
welp, guess it makes it pretty useless for a provider then, dont need customer A seeing customer B .... was hoping for more, time to deinstall

**Comment by DaVieS007** [comment]
Your reaction is opposite what you asked. I told you customer A does not sees customer B, and customers cannot create VMs, nor modify it. Its a provider complaint. Thats is what you exactly asked and answered. So no clue what are you meaning, but you are more than welcome to deinstall.

**Comment by outbackdingo** [comment]
I created a user, it cannot create a VM, whats the purpose then? I created 2 admins, both can see the others VMs. there is no partitioning or privacy, we dont want admin A) to see Admin B vms, i dont see where you explained that because its not what we see.

**Comment by DaVieS007** [comment]
Thank you for clarify your question now it makes sense to me. 
You should create VM through admin account and assign it to the user. Or do the same on API interface.

Once users is assigned to the VMs basic command will available to manage their VMs.
I dont see a purpose to allowing users to creating VMs.

**Comment by outbackdingo** [comment]
From a provider perspective, customers should be able to create / install their own vms which is why i started to look for ways to automate deployment, where in the other messages you suggested we "preinstalled disk image and create your own way to automatize through API interface" so yeah we are looking for a solution to serve customers.

**Comment by DaVieS007** [comment]
I understand by default I provide with this software a clean and basic interface which is mostly fit for multipurpose usage. You are looking into a more refined product for mass-vps hosting. These are mostly custom-made. No role/quota management planned to have in this software. ProxMox has.

In any other case I suggest to check up on API interface.
