### ISSUE TITLE
Mount points for VM storage

### ISSUE THREAD

**Issue by mayrk** [DaVieS007/bhyve-webadmin#34]
i am playing with the latest release an detected on a test machine that not all mountpoints are available.
Is there a limitation of 5 mountpoints or a name pattern which mountpoints are not available ?

For example on that machine the list of mountpoints contained /, /usr, /var, /tmp and /storage, but not /vm-storage.
I unmounted /storage, but /vm-storage was still not available in the list ...

I am a bit confused about what are valid names for the storage mountpoints ...

**Comment by DaVieS007** [comment]
Thanks to report this.
The software is using low-level api (getmntinfo()) [https://www.freebsd.org/cgi/man.cgi?query=getmntinfo&sektion=3&apropos=0&manpath=FreeBSD+14.0-current] fo fetch mounted paths on FreeBSD.

According the relevant manpage if mode is set to MNT_NOWAIT, getfsstat() will return the information it has available without requesting an update from each file system.  Thus, some of the information will be out of date, but getfsstat() will not block waiting for information from a file system that is unable to respond.  It will also skip any file system that is in the process of being unmounted, even if the unmount would eventually fail.

You can get vminfo() as RAW parameters that contains this information at [FS] section by invoking CLI Interface.

````
/var/lib/nPulse/BVCP/Backend/vmm cli
````

Or I might be the issues comes from if the mountpoint missing from fstab.

**Comment by mayrk** [comment]
I checked my /etc/fstab and all mountpoints are configured the same. I have no idea why only one of these is not visible.
I rearranged my file system mountpoints so i can use /storage which is shown in the list. :-)
