### ISSUE TITLE
PCI Passthrough

### ISSUE THREAD

**Issue by DaVieS007** [DaVieS007/bhyve-webadmin#4]
Add feature through the webinterface to support PCI Devices directly attached on the VM, like GPU.

**Comment by tatuzemdp** [comment]
Let me know if some beta tester are needed. Once we have this in... i can really start using bvcp.

**Comment by DaVieS007** [comment]
PCI Passthrough is available in recent release 2.0.0

**Comment by tatuzemdp** [comment]
Hey! That's good! Will give it a try

**Comment by tatuzemdp** [comment]
I have tired it and unless I am missing something, from my point of view I  believe it is not really useful as it is. 

 The reason for saying that is that there is no way from the WEB UI to see the ID of the PCI devices and their current status ( if it is attached to host, ready for ppt, etc).

I think it will be great to have:
- Hardware: something similar to "vm pass" where is shows the status of the device and their ID.
- Hardware: option to detach/attach/set driver/reset (devctl options).
- VM level:  drop down menu with available devices (that are not also used by another VM).

I know, easy to say, but it takes time and effort to do.
Btw, is not a complain just want to provide feedback.

**Comment by DaVieS007** [comment]
Thank you for sharing me this, I appreciate that.

Things are difficult, here's why.
At the moment the PCI Passthrough is working with BVCP, but you have to drop yourself into the shell and you better to know what you are doing.  So PCI Passthrough is very useful but not comfortable.

BVCP is yet does not have a proper documentation about PCI Passhtrough, working on it.

At the moment using PCI Passthrough is a very high risk to brick a system, especially if you are playing around with GPUs. 
In our tests using PCI passthrough easily leads to CRASH THE HOST.

We respect and share the FreeBSD legacy and we believe that some changes cannot be made with mouse-clicks and the PCI Passthrough is yet such a feature. Therefore despite **_we worked a lot further with PCI Passthrough_** on the frontend we decided to limit the user input, to protect our users from unwanted behaviors. 

PCI Passthrough is not a thing that you have to change frequently, but we looking forward to improve this feature.
Listing masked devices and put a checkbox front of them is not a big deal, but the hard thing is protect the system and users to make something stupid and needs more time and discussion about these.

Even so, I have to say that we worked hard in the past days to fix such problems that wasnt appeared on our tests.
BVCP is running on hundreds of different servers and things are working differently, I could not take a responsibility for a dropdown menu at the moment and I think the most of BVCP users expect that to not doing so.

If in the future when FreeBSD allows more control over PCI devices without crash or reboot, will be integrated. 
At the moment the success of PCI Passthrough is depending on the user skills, so adding dropdown might be misleading and people will blame BVCP when something goes wrong.
