### ISSUE TITLE
1.9.8p6 does not install/run proper under FreeBSD 13.2

### ISSUE THREAD

**Issue by xatru42** [DaVieS007/bhyve-webadmin#42]
Wanted to give BVCP a try so deployed fresh 13.2R. install.sh script runs and finishes as per documentation providing portal password credentials. However, last output is "graceful shutdown" of the frontserver. The log shows:

[S] 2023-09-07 16:04:16 | Logger | *** START LOGGING ***
[N] 2023-09-07 16:04:16 | Daemon/Start | BVCP Bhyve WebUI Controller
[N] 2023-09-07 16:04:16 | bootCode | Started as Daemon Mode
[N] 2023-09-07 16:04:16 | Guardian | Create Process, PID: 1358
[N] 2023-09-07 16:04:16 | SW | VFS:BuiltIn Loaded
[N] 2023-09-07 16:04:16 | ThreadPool | 10/10 Threads initialised
[N] 2023-09-07 16:04:16 | LVM::MAIN | Initialising ..
[N] 2023-09-07 16:04:16 | application/vmclient/main.c | Initialising BVCP Application
[N] 2023-09-07 16:04:16 | application/vmclient/main.c | Using configuration file: /var/lib/nPulse/BVCP/bvcp.conf
[N] 2023-09-07 16:04:16 | application/vmclient/main.c | SSL Certificate Store Loaded
[N] 2023-09-07 16:04:16 | application/vmclient/main.c | Re-Load SSL Certificates Successfull
[N] 2023-09-07 16:04:16 | application/vmclient/main.c | Securing environment before we opening for connections ..
[N] 2023-09-07 16:04:18 | application/vmclient/main.c | Starting Software ...
[E] 2023-09-07 16:04:18 | application/vmclient/main.c | No configuration for authentication node!
[N] 2023-09-07 16:04:18 | SW | Program exited gracefully...

So it complains that there is no authentication node, probably something simple but couldn't find any docu how that is configured... to bad.

**Comment by xatru42** [comment]
trying to "reset" pw gives new credentials, but issues remains the same:

 N  2023-09-07 16:18:31 | BVCP | Initialising BVCP-Backend 1.9.8-p6 Application
 N  2023-09-07 16:18:32 | BVCP | Starting Database ...
 (!) Admin Credentials recreated,
   - User: admin
   - Password: 3IicXvtS

 N  2023-09-07 16:18:32 | SW | Program exited gracefully...

**Comment by xatru42** [comment]
turns out, if you VERY fresh install it, it doesn't see hostname and config is created with empty fields... so install doesn't complain and would assume above error is a side effect of missing sanity check.

**Comment by DaVieS007** [comment]
Thanks your feedback, Im going to check the issue anyway.
