### ISSUE TITLE
libc++ Unsupported relocation type after upgrade

### ISSUE THREAD

**Issue by innerteapot** [DaVieS007/bhyve-webadmin#43]
When running the update script from p6 to p7 I encountered this error when the services tried to restart:

`ld-elf.so.1: /usr/lib/libc++.so.1: Unsupported relocation type 60020 in non-PLT relocations`

I'm on the the latest patch level of FreeBSD 13.

```
# freebsd-version
13.2-RELEASE-p5
# uname -a
FreeBSD test.genesis.net.au 13.2-RELEASE-p4 FreeBSD 13.2-RELEASE-p4 GENERIC amd64
```

I rebooted and the services started ok but I could not start / noVNC to any VM's from the web interface. 

I ran the update script again and the services restarted without any errors. 

Everything seems to be working normally now. Still thought it best to report anyway just in case the update process can be improved in any way. Please and thank you :)

**Comment by DaVieS007** [comment]
Thank you for sharing this. I believe this error should come from OS level. 
So I think this situation can occurs when if you updated the previous FreeBSD system before, but without perform a reboot, that possibly cause the old libararies invalidates when trying to execute or load another binary, therefore the installer could not run properly and the upgrade process halted.

Mostly affected libraries to this is openssl library. 
If you have any update or new occurance of this case, please let me know and we going to look further.

Thanks your feedback.
