### ISSUE TITLE
VM name missing from dashboard

### ISSUE THREAD

**Issue by SirHumphreyAppleby** [DaVieS007/bhyve-webadmin#44]
Clean install of BVCP 1.9.8-p8. VM names are missing from the dashboard. When I click on "vm /", I am taken to the VM with the correct name "vm / freebsd14builder".

![missing](https://github.com/DaVieS007/bhyve-webadmin/assets/1866419/d0d4ede7-e5cc-4851-a1d3-172db7100341)

FreeBSD 14.0-RELEASE-p3 amd64

**Comment by DaVieS007** [comment]
Thank you for letting me know this.
We could not yet reproduce the error.
Can I have a screenshot from the VM page?

**Comment by SirHumphreyAppleby** [comment]
If it's relevant, the name was entered as "FreeBSD 14 Builder".

![missing2](https://github.com/DaVieS007/bhyve-webadmin/assets/1866419/16413a29-a875-49f1-b188-d5d3af1ca983)

**Comment by DaVieS007** [comment]
Thanks.
Can you enter a new name by clicking on the right pane, Name / Description field?

**Comment by SirHumphreyAppleby** [comment]
Ah. I assumed the dashboard would show the name, not the description. I don't normally add descriptions if the name provides all the information I need.

**Comment by DaVieS007** [comment]
Fair point, if no descriptive name provided it should fallback to it's "name".

**Comment by DaVieS007** [comment]
FYI. 
v.1.9.8-p9 (UPCOMING_RELEASE)
2023.12.29: Showing VM's name instead at dashboard when no descriptive text provided
