### ISSUE TITLE
[Feature Request] Add support for UEFI variables

### ISSUE THREAD

**Issue by SirHumphreyAppleby** [DaVieS007/bhyve-webadmin#45]
Bhyve in FreeBSD 14 (possibly added to later 13.x releases) supports UEFI variables.

Adding support for this will avoid having to manually edit the boot configuration each time I setup a Linux (Debian in my case) VM.

**Comment by DaVieS007** [comment]
From version 2.x this will be available along with PCI Passthrough.

**Comment by DaVieS007** [comment]
Yup, done.
