### ISSUE TITLE
Validation of VM name (and other details)

### ISSUE THREAD

**Issue by SirHumphreyAppleby** [DaVieS007/bhyve-webadmin#46]
Related to #44, it is currently possible to create a VM without a name.

When you do so, the resulting VM appears in the list of VMs (Dashboard and Virtual Machines pages), but clicking on VM in the Dashboard just takes you to the Virtual Machines page and the settings button goes nowhere. It's not possible to delete the VM from within the UI.

![Untitled](https://github.com/DaVieS007/bhyve-webadmin/assets/1866419/7a76bcb6-e0a3-4d37-a43c-0238b254dfc4)

I removed the created VM from _machines_ entry in the database.

**Comment by DaVieS007** [comment]
Thank you for letting me know this.

I could reproduce this issue and identified what breaks this feature.
The fix will also include to rename empty instance if exists.

**Comment by DaVieS007** [comment]
The fix has been made for this issue and will be released with the next patch v.1.9.8-p9
The fix also solves inaccessible VM by giving it a new name.



![Screenshot_257](https://github.com/DaVieS007/bhyve-webadmin/assets/12925556/b02be9f5-e559-49cb-8306-ff7bf15fefc5)
