### ISSUE TITLE
Changing password for admin user does not work

### ISSUE THREAD

**Issue by strandte** [DaVieS007/bhyve-webadmin#48]
I have a clean FreeBSD 14 installation where I have installed bhyve and bhyve-webadmin. When I logged in I was not able to change the password for admin. The issue is similar to this one: https://github.com/DaVieS007/bhyve-webadmin/issues/22
In addition my root account is now locked out, even if I did not use it. 
I managed to register two users, but none of them are able to log in to the web interface.
Do someone have a clue what might be wrong? I use the release version of bhyve-webadmin.

**Comment by DaVieS007** [comment]
Please allow us some time to reproduce the issue, in the meantime you able to change your password under Users Management section. YOU_IP:8086/admin/users

If your account is locked out, you can restart the service daemon which will flush all bans, 
by issuing: ```` service bvcp-frontend restart ````

Any other circumstances the CLI interface could be very handy, by issuing: ```` /var/lib/nPulse/BVCP/Backend/vmm cli ````

**Comment by strandte** [comment]
Thanks for the good clues to what I could do to solve this. I found out that the two users was actually able to log in, only I had to use the mail address as username. My advice would be for you to make a grayed out tip in the username textbox hinting to email address as login/user. The first time we log in we use "admin" as login, so I was led to believe that a similar username would be used for the other users as well.

**Comment by strandte** [comment]
The root user was not locked out. I'm not so familiar with FreeBSD yet, so it took some time to release that I could not login via ssh with root, and that I was not able to use "su" or "sudo" without installing and configuring this. 
Do we actually need the "Admin" user we log in with the first time, or is this account only used this one time and later disabled automatically? The password change that did not work was for this "Admin" user. Maybe this is the intention, since it seems to be a one time user?

**Comment by DaVieS007** [comment]
The admin user is not a one-time thing. 
You can set a proper email address on the administration section, then you are allowed to change the password.
We will make a fancy UI in version 2.0 to address this for any newcomers.

**Comment by strandte** [comment]
Thanks for the quick answers. The Web-GUI BVCP/bhyve-WebAdmin looks nice. I will test it out the next days. If it hadn't been for your work on this I do not think I would have chosen Bhyve even if it has some pretty nice features when compared to the competitors. Hope others see this also, and that your work will contribute to it's market share.

**Comment by DaVieS007** [comment]
Thanks your review about BVCP, after all I think you will love the version 2.0.0 which has better, faster and more stable UI.
Also I'm commenting here due in fact the original problem is solved by adding alert and modal for get rid of admin as invalid email.

![Screenshot_320](https://github.com/DaVieS007/bhyve-webadmin/assets/12925556/a573f8f8-7565-4553-abfa-7905820d77f5)
![Screenshot_321](https://github.com/DaVieS007/bhyve-webadmin/assets/12925556/f3f37178-9342-48b4-86fa-9f0cd60202bf)
