### ISSUE TITLE
Journal: Failed to create UEFI Storage

### ISSUE THREAD

**Issue by amutu** [DaVieS007/bhyve-webadmin#55]
host is FreeBSD 14.0, gust is FreeBSD 14.0 too.
I have already installed bhyve-firmware.
BVCP v2.1.2.

system log：
 [E] 2024-03-29 16:42:09 | BVCP | Backend[freebsd14] Report Detailed Error: push
     the index 'BHYVE_UEFI_VARS' does not exist at bhyve/vm_core.class.c(540)
      ********************** VM INTERNAL ERROR **********************
     	[*] Stack Traceback:
     		[0] utils/connectionManager.class.c(293)::OnData
     		[CATCH] bhyve/vm_core.class.c(540)::startVM
     		[1] utils/tcpServer.class.c(280)::dispatch
     		[2] utils/tcpServer.class.c(336)::poll
     		[3] utils/DProtocolServer.class.c(727)::poll
     		[4] application/vmserver/api/api.c(96)::thread_main
     		[5] utils/thread.class.c(359)::main
      *************************************************************** 

vm gust config:
![bhy](https://github.com/DaVieS007/bhyve-webadmin/assets/3396938/32634b95-fbb3-4cb4-b064-829cdb2b1a52)

**Comment by DaVieS007** [comment]
Thanks your feedback and reportig the issue.

The only error here, that the error message missing quotes, which will be fixed as a patch.
Your problem is BHYVE_UEFI_VARS.fd missing which is located - by default - at /vms/bootrom/ folder.
These folder should be created and populated by the restarting bvcp-backend.

**Comment by amutu** [comment]
Yes，/vms dataset do not exist when I install bvcp，but bvcp started OK. It is better to create /vms auto when install or refuse to start when /vms do not exist.
I am afraid there may have some other subdirs I missing? Is there some doc about the dir hierarchies？ Or I should reinstall bvcp?

**Comment by DaVieS007** [comment]
The installer should create those directories, so I recommend to re-install.
